header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: TiDB Project Authors.
  paths:
    - '**/*.java'
  paths-ignore:
    - '**/target'
    - 'tidb/src/main/java/io/tidb/bigdata/tidb/parser/gen/MySqlLexer.java'
  comment: on-failure